### ISSUE TITLE
Error: Could not locate the bindings file. 

### ISSUE THREAD

**Issue by obzva** [source-academy/sicp#888]
I am new to node. Could you help me handle this error? It occurred while I imported `pair`function from `sicp` library.
Or It could also be nice that anybody help me to find out where I can read the implementation of this actual function `pair`.

I ran this code
```
import { pair } from "sicp";

const x = pair(1, 2);
head(x);
```
and this error appeared.
```
/Users/obzva/.nvm/versions/node/v19.6.0/bin/node /Users/obzva/SICP_JS/chapter_2/the_big_code.js
/Users/obzva/SICP_JS/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /Users/obzva/SICP_JS/node_modules/gl/build/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/build/Debug/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/build/Release/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/out/Debug/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/Debug/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/out/Release/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/Release/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/build/default/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/compiled/19.6.0/darwin/arm64/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/addon-build/release/install-root/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/addon-build/debug/install-root/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/addon-build/default/install-root/webgl.node
 → /Users/obzva/SICP_JS/node_modules/gl/lib/binding/node-v111-darwin-arm64/webgl.node
    at bindings (/Users/obzva/SICP_JS/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/obzva/SICP_JS/node_modules/gl/src/javascript/native-gl.js:1:40)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/obzva/SICP_JS/node_modules/gl/src/javascript/webgl-rendering-context.js:4:58)
    at Module._compile (node:internal/modules/cjs/loader:1246:14) {
  tries: [
    '/Users/obzva/SICP_JS/node_modules/gl/build/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/build/Debug/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/build/Release/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/out/Debug/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/Debug/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/out/Release/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/Release/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/build/default/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/compiled/19.6.0/darwin/arm64/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/addon-build/release/install-root/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/addon-build/debug/install-root/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/addon-build/default/install-root/webgl.node',
    '/Users/obzva/SICP_JS/node_modules/gl/lib/binding/node-v111-darwin-arm64/webgl.node'
  ]
}

Node.js v19.6.0

Process finished with exit code 1

```

and here is my package.json
```
{
  "name": "sicp",
  "version": "1.0.0",
  "description": "My record of studying SICP",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/obzva/SICP_JS.git"
  },
  "author": "obzva <dngyng1000@gmail.com>",
  "license": "MIT",
  "devDependencies": {
    "prettier": "^2.8.7"
  },
  "dependencies": {
    "sicp": "^1.1.4"
  },
  "type": "module",
  "bugs": {
    "url": "https://github.com/obzva/SICP_JS/issues"
  },
  "homepage": "https://github.com/obzva/SICP_JS#readme",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}

```

**Comment by martin-henz** [comment]
See  https://about.sourceacademy.org/package/
